### PR TITLE
Better SFX & Music, User Configs & Channels, many more...

### PR DESCRIPTION
**Pull request by ktg5**
Took some time today to make some improvements to this repo.
* Better SFX & Music + Howler.js
* User configuration & channels using Local Storage
* Warning Splash
* Fixed some bugs & other stuff that ain't that special.

### CODE REVIEW

**Comment by jerosajose** [comment]
I'll fully review it on the weekend as I don't have much time now, but I'll call out a few things that quite annoy me:

- Don't use .wav files. They're generally big files, and I'm not really into audio quality here, so it's best to go with mpeg-3.
- Don't use images to show text (like in the splash screen image). If it's text, it should be written in the HTML files and styled with CSS.
- Avoid the use of JavaScript. I've seen some basic animations ran with JS, that could be simply done with CSS timed transitions like fadeIn and fadeOut.
- Don't delete CSS classes, even if they're unused. I'll do a cleanup if necessary, but don't delete them.
- Don't rename "generic" CSS keyframes animations already defined and written by me, like fadeIn. I've found another "fadeInStatic" which is completely unnecessary, as "fadeIn" was already written and has a shorter and appealing name.

The rest of it is pretty decent, thanks for the job done with some JavaScript there simplifying some channels stuff. Do some tweaks taking into account all the points I just mentioned and I'll merge the PR soon.

About the real website uploaded to the link in the repo, it'll be updated hopefully on Christmas holiday, as I still have to take my hands on the next update to fix little stuff from the site.

**Comment by ktg5** [comment]
Thanks for the reply! I'll be getting to all of this when I can. I would like to note that the warning splash actually uses raw HTML & CSS, because I think it'd be a bit easier to edit.
image
In the earlier commits, there was an image used for the warning splash, but that has been changed.

There was one thing I forgot to talk about that shouldn't be high priority or anything that I didn't want to do myself, but maybe merge everything in the `channelart` folder with everything in the `assests/channels` folder? Might be a bit easier to manage.

**Comment by jerosajose** [comment]
Cool! Good to hear that.

Regarding the `channelart` thing, I haven't merged those folders because I don't include HTML pages in the "assets" folder. I always reserve that folder for media and SFX used in the website, but never to be used as parts or the whole website itself, maybe you get my point.

**Comment by jerosajose** [comment]
I'm sorry, but I couldn't review it this weekend. I'm pretty busy at the moment with studies, and will be until almost Christmas.

I hope you don't mind if this takes some extra time until my so waited Christmas holidays lol (I need a break from school seriously).

I've also seen some recent changes! Correcting misspelled variables and stuff, nice.

Sorry again, and cheers.

**Comment by ktg5** [comment]
All good! Take as much time as you need.

**Comment by jerosajose** [comment]
Let's continue this conversation on Discord ;)

**Review by jerosajose — CHANGES_REQUESTED** [review]
Changes in the Discord DMs.

**Review by jerosajose — APPROVED** [review]
Great! I'll add more information to the PWA manifest later

**Pull request merged**
